remote_theme: rundocs/jekyll-rtd-theme
title: OpenBMP

lang: en
description: OpenBMP Documentation
url: "https://www.openbmp.org"

lsi: true
safe: true

html_logo: "images/logo-sidebar.png"
html_favicon: "images/favicon.ico"

readme_index:
  with_frontmatter: true

show_sorted: false

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-mentions
